---
# tasks file for deploy_nginx
- name: Deploy webserver with nginx
  become: true
  hosts: all

  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        update_cache: true

    - name: Systemd enable nginx
      systemd:
        state: started
        enabled: true
        name: nginx

    - name: Disable the default site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Copy the nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/conf.d

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
