---
# tasks file for deploy_nginx
- name: deploy webserver with nginx
  become: True
  hosts: all

  tasks:
    - name: install nginx
      dnf:  
        name: nginx 
        update_cache: yes
      
    - name: systemd enable nginx
      systemd:
        state: started
        enabled: yes
        name: nginx