- name: Setup hostnames
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: "systemd"

- name: Change hosts file
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for item in groups.vm %}
      {{hostvars[item].ansible_host}}	{{ hostvars[item].inventory_hostname }}
      {% endfor %}

- name: Ensure the highavailability and resilientstorage repositories are enabled
  community.general.dnf_config_manager:
    name:
      - highavailability
      - resilientstorage
    state: enabled

- name: Install common packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    update_cache: true

- name: Start services
  ansible.builtin.systemd_service:
    name: pcsd
    state: started
    enabled: true

- name: Start services
  ansible.builtin.systemd_service:
    name: lvmlockd
    state: started
    enabled: true
